import test0 from './Test/0_Statement/0_Normal/Normal';
import test1 from './Test/0_Statement/1_Split/Split';
import test2 from './Test/0_Statement/2_Nested/Nested';
import test3 from './Test/0_Statement/3_Abuse/Abuse';
import test4 from './Test/1_Branch/0_Normal/ConditionalOperator';
import test5 from './Test/1_Branch/0_Normal/If';
import test6 from './Test/1_Branch/0_Normal/ShortCircuitEvaluation';
import test7 from './Test/1_Branch/0_Normal/Switch';
import test8 from './Test/1_Branch/1_Split/ConditionalOperator';
import test9 from './Test/1_Branch/1_Split/If';
import test10 from './Test/1_Branch/1_Split/ShortCircuitEvaluation';
import test11 from './Test/1_Branch/1_Split/Switch';
import test12 from './Test/1_Branch/2_Nested/ConditionalOperator';
import test13 from './Test/1_Branch/2_Nested/If';
import test14 from './Test/1_Branch/2_Nested/ShortCircuitEvaluation';
import test15 from './Test/1_Branch/2_Nested/Switch';
import test16 from './Test/1_Branch/3_Abuse/ConditionalOperator';
import test17 from './Test/1_Branch/3_Abuse/If';
import test18 from './Test/1_Branch/3_Abuse/ShortCircuitEvaluation';
import test19 from './Test/1_Branch/3_Abuse/Switch';
import test20 from './Test/2_Function/0_Normal/ArrowFunction';
import test21 from './Test/2_Function/0_Normal/ClassMethod';
import test22 from './Test/2_Function/0_Normal/FunctionDeclaration';
import test23 from './Test/2_Function/0_Normal/FunctionExpression';
import test24 from './Test/2_Function/1_Split/ArrowFunction';
import test25 from './Test/2_Function/1_Split/ClassMethod';
import test26 from './Test/2_Function/1_Split/FunctionDeclaration';
import test27 from './Test/2_Function/1_Split/FunctionExpression';
import test28 from './Test/2_Function/2_Nested/ArrowFunction';
import test29 from './Test/2_Function/2_Nested/ClassMethod';
import test30 from './Test/2_Function/2_Nested/FunctionDeclaration';
import test31 from './Test/2_Function/2_Nested/FunctionExpression';
import test32 from './Test/2_Function/3_Abuse/ArrowFunction';
import test33 from './Test/2_Function/3_Abuse/ClassMethod';
import test34 from './Test/2_Function/3_Abuse/FunctionDeclaration';
import test35 from './Test/2_Function/3_Abuse/FunctionExpression';

it('runs test to verify coverage reports', () => {
  test0();
  test1();
  test2();
  test3();
  test4();
  test5();
  test6();
  test7();
  test8();
  test9();
  test10();
  test11();
  test12();
  test13();
  test14();
  test15();
  test16();
  test17();
  test18();
  test19();
  test20();
  test21();
  test22();
  test23();
  test24();
  test25();
  test26();
  test27();
  test28();
  test29();
  test30();
  test31();
  test32();
  test33();
  test34();
  test35();
});
